### ISSUE TITLE
View and use MOC tokens rewards

### ISSUE THREAD

**Issue by jacobburrell** [money-on-chain/main-RBTC-contract#33]
Is there a way to use MOCs rewarded for holding BitPros?

I looked at adding a custom token such as BitPRO looking up the contract's address: https://github.com/money-on-chain/main-RBTC-contract/blob/master/Contracts%20verification.md

Adding 0x8e065bf32bb68c1a32e37d7276f8c8dd5545e029 for a custom token called MOC does not seem to work correctly.

I have BitPROs working fine.

![image](https://user-images.githubusercontent.com/61520543/101602517-1a69c280-39b3-11eb-9e20-d2b327d7abd4.png)

**Comment by MoneyOnChain** [comment]
Hi jacobburrell, thanks for your comnet,
The cotract you mention is not the token MoC Contract, indeed still there is not such token in mai. It wil be available in 1st quarter 2021. The ammount of MoCs you can see in the rewards counter is just a counter and those tokens will be distributed as I saiid in 1st quarter 2021. Best regars.
